### ISSUE TITLE
Development Environment 

### ISSUE THREAD

**Issue by sfranzyshen** [cpq/mjs3#2]
Hi,

I have been following mjs (v7) for awhile now ... I noticed this fork and I'm curious about it's direction ... I also have been trying to compile it using the arduino ide ... but I end up with errors ... can you tell more about what your development environment is (versions would be great) so that perhaps I can follow along ... I've been looking into the possibility of running mjs as a library within the Arduino IDE environment ... Below are the build errors I encounter ... I am able to REM out the lines of the first set of errors ... to get up to the linking stage ... but not much I can do past that ...

USING: Arduino: 1.8.9 (Windows Store 1.8.21.0) (Windows 10), Board: "Arduino Nano, ATmega328P (Old Bootloader)"

```
Compiling sketch...
"\hardware\\tools\\avr/bin/avr-gcc" -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10809 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-I\hardware\\arduino\\avr\\cores\\arduino" "-I\hardware\\arduino\\avr\\variants\\eightanaloginputs" "\Local\\Temp\\arduino_build_974734\\sketch\\mjs3.c" -o "\Local\\Temp\\arduino_build_974734\\sketch\\mjs3.c.o"

\Local\Temp\arduino_build_974734\sketch\mjs3.c: In function 'do_op':

mjs3.c:846:43: error: duplicate case value

     case DT('>', '>'): case DT('<', '<'): case TT('>', '>', '>'):

                                           ^

mjs3.c:846:5: error: previously used here

     case DT('>', '>'): case DT('<', '<'): case TT('>', '>', '>'):

     ^

mjs3.c:866:5: error: duplicate case value

     case QT('>', '>', '>', '='):  return do_assign_op(p->vm, TT('>', '>', '>'));

     ^

mjs3.c:865:5: error: previously used here

     case TT('>', '>', '='): return do_assign_op(p->vm, DT('>', '>'));

     ^

exit status 1
duplicate case value


```
after remming out the lines with errors above ... I tried linking and get the following errors ...

```
Linking everything together...
"\hardware\\tools\\avr/bin/avr-gcc" -w -Os -g -flto -fuse-linker-plugin -Wl,--gc-sections -mmcu=atmega328p -o "\Local\\Temp\\arduino_build_974734/mjs3.ino.elf" "\Local\\Temp\\arduino_build_974734\\sketch\\mjs3.c.o" "\Local\\Temp\\arduino_build_974734\\sketch\\mjs3.ino.cpp.o" "\Local\\Temp\\arduino_build_974734/..\\arduino_cache_603274\\core\\core_arduino_avr_nano_cpu_atmega328old_180a539c02cce575fcd7710170113f75.a" "-L\Local\\Temp\\arduino_build_974734" -lm\Local\Temp\arduino_build_974734\sketch\mjs3.ino.cpp.o (symbol from plugin): In function `myDelay':

(.text+0x0): multiple definition of `mjs_to_str'

\Local\Temp\arduino_build_974734\sketch\mjs3.c.o (symbol from plugin):(.text+0x0): first defined here

\Local\Temp\arduino_build_974734\sketch\mjs3.ino.cpp.o (symbol from plugin): In function `myDelay':

(.text+0x0): multiple definition of `mjs_set'

\Local\Temp\arduino_build_974734\sketch\mjs3.c.o (symbol from plugin):(.text+0x0): first defined here

\Local\Temp\arduino_build_974734\sketch\mjs3.ino.cpp.o (symbol from plugin): In function `myDelay':

(.text+0x0): multiple definition of `mjs_create'

\Local\Temp\arduino_build_974734\sketch\mjs3.c.o (symbol from plugin):(.text+0x0): first defined here

\Local\Temp\arduino_build_974734\sketch\mjs3.ino.cpp.o (symbol from plugin): In function `myDelay':

(.text+0x0): multiple definition of `mjs_destroy'

\Local\Temp\arduino_build_974734\sketch\mjs3.c.o (symbol from plugin):(.text+0x0): first defined here

\Local\Temp\arduino_build_974734\sketch\mjs3.ino.cpp.o (symbol from plugin): In function `myDelay':

(.text+0x0): multiple definition of `mjs_eval'

\Local\Temp\arduino_build_974734\sketch\mjs3.c.o (symbol from plugin):(.text+0x0): first defined here

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino Nano.

```

any insight? ... Thank You!

**Comment by sfranzyshen** [comment]
I have managed to compile (not run) the blink example sketch from the project github web page for the esp8266 using the Arduino IDE (1.8.9 ) by making the following changes to the current (8/19/2019) code ... [commit](https://github.com/sfranzyshen/mjs3/commit/387d9d559a98aea9f842def14c49b32383d56e7f)

I am still encountering the "duplicate case value" errors when targeting AVR (atmega328p) boards ... why does this work for other gcc (gcc-xtensa) targets and not the gcc-avr??

**Comment by sfranzyshen** [comment]
I have the current code working with the Arduino IDE (1.8.9 ) on a NodeMCU v1.0 ESP8266 board. I have slightly modified the mjs3.c file in order to compile ... then using the following sketch from the project readme ...

```
#define MJS_STRING_POOL_SIZE 200      // Buffer for all strings
#include "mjs3.c"                     // Sketch -> Add File -> mjs3.c

extern void myDelay(int x) { 
  delay(x);
}

extern void myDigitalWrite(int x, int y) {
  digitalWrite(x, y);
}

void setup() {
  pinMode(16, OUTPUT);                                  // Initialize the LED_BUILTIN pin as an output

  struct mjs *vm = mjs_create();                        // Create JS instance
  mjs_ffi(vm, "delay", (cfn_t) myDelay, "vi");          // Import delay()
  mjs_ffi(vm, "write", (cfn_t) myDigitalWrite, "vii");  // Import write()

  mjs_eval(vm, "while (1) { write(16, 0); delay(500); write(16, 1); delay(500); }", -1); // evaluate the JS ...

}

void loop() {
  //delay(1000);
}
```

**Comment by sfranzyshen** [comment]
I'm still looking for a solution to the duplicate case value errors when trying to do a AVR build ...

**Comment by sfranzyshen** [comment]
Comparing a basic Blink sketch with a mjs3 blink sketch ... it compiles small :)
```
// Blink

void setup() {
  pinMode(16, OUTPUT);             // Initialize the LED_BUILTIN pin as an output
}

// the loop function runs over and over again forever
void loop() {
  digitalWrite(16, LOW);           // Turn the LED on (Note that LOW is the voltage level
  delay(500);                      // Wait for a second
  digitalWrite(16, HIGH);          // Turn the LED off by making the voltage HIGH
  delay(500);                      // Wait for two seconds (to demonstrate the active low LED)
}
```

Sketch uses 258948 bytes (24%) of program storage space. Maximum is 1044464 bytes.
Global variables use 26588 bytes (32%) of dynamic memory, leaving 55332 bytes for local variables. Maximum is 81920 bytes.

```
// mjs3 Blink

#define MJS_STRING_POOL_SIZE 200      // Buffer for all strings
#include "mjs3.c"                     

extern void myDelay(int x) { 
  delay(x);
}

extern void myDigitalWrite(int x, int y) {
  digitalWrite(x, y);
}

void setup() {
  pinMode(16, OUTPUT);                                  // Initialize pin as an output
  
  struct mjs *vm = mjs_create();                        // Create JS instance
  mjs_ffi(vm, "delay", (cfn_t) myDelay, "vi");          // Import delay()
  mjs_ffi(vm, "write", (cfn_t) myDigitalWrite, "vii");  // Import write()
  
  mjs_eval(vm, "while (1) { write(16, 0); delay(500); write(16, 1); delay(500); }", -1); // Evaluate JS instance
}

void loop() {
  //delay(1000);
}
```

Sketch uses 273148 bytes (26%) of program storage space. Maximum is 1044464 bytes.
Global variables use 27828 bytes (33%) of dynamic memory, leaving 54092 bytes for local variables. Maximum is 81920 bytes.

**Comment by sfranzyshen** [comment]
moving on ...
